'use strict';
const data=JSON.parse(document.getElementById('data').textContent),episode=data.episode,view=data.view;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
document.getElementById('label').textContent=`${episode.agent} · ATTEMPT ${episode.attempt} · SEED ${episode.seed??'unrecorded'}`;
document.getElementById('title').textContent=episode.task.replaceAll('_',' ');
document.getElementById('instruction').textContent=typeof view.task==='string'?view.task:'';
const badges=document.getElementById('badges');for(const [label,value] of [['Original',episode.success],['Corrected',episode.success_corrected]])badges.append(el('span',`${label}: ${value?'PASS':'FAIL'}`,`badge ${value?'pass':'fail'}`));badges.append(el('span',`Task pack ${episode.task_pack_version??'unrecorded'}`,'badge'));
const video=document.getElementById('video');if(episode.video)video.src=episode.video;else video.hidden=true;
const coverage=document.getElementById('coverage');coverage.append(el('strong','Transcript coverage'));const c=view.coverage||{};
for(const [label,value] of [['Representation',view.source.kind],['Turns',episode.turn_count],['Thinking text',c.turns_with_thinking_text],['Token evidence only',c.turns_with_thinking_evidence_only],['Joined tool results',c.server_outcomes_joined],['Wall time',episode.wall_s==null?null:`${(episode.wall_s/60).toFixed(1)} min`]])if(value!=null)coverage.append(el('p',`${label}: ${value}`,'note'));
if(view.source.kind==='vendor')coverage.append(el('p','A turn is a normalized assistant stream event, not necessarily a complete model inference.','note'));
function pretty(value){return JSON.stringify(value,null,2);}
function imagesFor(call){const text=JSON.stringify(call.result||{});const ids=[...new Set(text.match(/obs_\d+(?:_a\d+)?/g)||[])];const files=new Set();for(const id of ids)for(const file of episode.observations[id]||[])files.add(file);return [...files];}
function render(){const query=document.getElementById('search').value.toLowerCase();const target=document.getElementById('turns');target.replaceChildren();const turns=view.turns||[{turn:'unavailable',tool_calls:view.calls||[],text:view.turns_unavailable_reason}];
for(const turn of turns){if(query&&!JSON.stringify(turn).toLowerCase().includes(query))continue;const card=el('article',null,'turn');card.append(el('h2',`Turn ${turn.turn}`));if(turn.observations_in?.length)card.append(el('p',`Input from: ${turn.observations_in.join(', ')}`,'note'));if(turn.thinking)card.append(el('div',turn.thinking,'text thinking'));else if(turn.thinking_evidence)card.append(el('p',`Reasoning text unavailable · ${turn.thinking_evidence.estimated_tokens??0} estimated reasoning tokens recorded`,'note'));if(turn.text)card.append(el('div',turn.text,'text'));
for(const call of turn.tool_calls||[]){const details=el('details',null,'call');details.append(el('summary',`${call.id} · ${call.tool}${call.dispatched?'':' · no server dispatch recorded'}`));let loaded=false;details.addEventListener('toggle',()=>{if(!details.open||loaded)return;loaded=true;details.append(el('p','Arguments','note'),el('pre',pretty(call.args)));details.append(el('p','Result','note'),el('pre',call.result==null?pretty(call.result_summary||'No result recorded'):pretty(call.result)));});card.append(details);const files=imagesFor(call);if(files.length){const strip=el('div',null,'images');for(const file of files){const a=el('a');a.href=file;a.target='_blank';a.rel='noopener';const img=el('img');img.src=file;img.loading='lazy';img.alt=file.split('/').pop();a.append(img);strip.append(a);}card.append(strip);}}
if(turn.usage){const d=el('details',null,'call');d.append(el('summary','Usage'),el('pre',pretty(turn.usage)));card.append(d);}target.append(card);}
if(!target.children.length)target.append(el('p','No matching turns.','empty'));}
document.getElementById('search').addEventListener('input',render);render();
