#!/usr/bin/env python3
"""Render the vendor CLI integration reference from runtime declarations.

Run: python3 tools/render_vendor_checklist.py [--check]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
if str(PROJECT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT / "src"))

from codeaction.agents.vendor.clis import VENDOR_CLIS  # noqa: E402
from codeaction.agents.vendor.contract import (  # noqa: E402
    BANNED, DISPOSITIONS, EVIDENCE_KINDS, REQUIRED)

DOC = PROJECT / "docs" / "vendor-cli-onboarding.md"


def _cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def _capability_table(items) -> list[str]:
    rows = ["| Capability | Requirement | Evidence |",
            "|---|---|---|"]
    for item in items:
        rows.append(
            f"| `{item.id}` | {_cell(item.summary)} | "
            f"{', '.join(f'`{kind}`' for kind in item.evidence)} |")
    return rows


def _seat_table(cli) -> list[str]:
    rows = ["| Capability | State | Evidence | Mechanism |", "|---|---|---|---|"]
    for item in cli.dispositions:
        rows.append(
            f"| `{item.capability}` | {item.state} | `{item.evidence}` | "
            f"{_cell(item.mechanism)} |")
    return rows


def _asymmetries() -> list[str]:
    """Where two seats answer the same contract line differently. Computed, never remembered."""
    seats = list(VENDOR_CLIS.values())
    rows = ["| Capability | " + " | ".join(f"`{cli.name}`" for cli in seats) + " |",
            "|---" * (len(seats) + 1) + "|"]
    found = False
    for item in REQUIRED + BANNED:
        cells = [
            f"{cli.disposition(item.id).state} / `{cli.disposition(item.id).evidence}`"
            for cli in seats]
        if len(set(cells)) > 1:
            found = True
            rows.append(f"| `{item.id}` | " + " | ".join(cells) + " |")
    if not found:
        return ["Every seated CLI answers every contract line identically."]
    return rows


def render() -> str:
    seats = list(VENDOR_CLIS.values())
    lines = [
        "# Vendor CLI integration reference",
        "",
        "<!-- Generated by tools/render_vendor_checklist.py from the vendor declarations. -->",
        "",
        "Vendor agents use the benchmark's MCP interface. Each declaration specifies a pinned",
        "CLI version, credential mount, container service, stream normalizer and capability",
        "configuration. The tables below are generated from those declarations.",
        "",
        "## Evidence kinds",
        "",
        "| Kind | Source |",
        "|---|---|",
    ]
    for kind, description in EVIDENCE_KINDS.items():
        lines.append(f"| `{kind}` | {_cell(description)} |")
    lines += ["", "## Capability states", "", "| State | Meaning |", "|---|---|"]
    for state, description in DISPOSITIONS.items():
        lines.append(f"| `{state}` | {_cell(description)} |")
    lines += [
        "", f"## Required capabilities ({len(REQUIRED)})", "", *_capability_table(REQUIRED),
        "", f"## Restricted capabilities ({len(BANNED)})", "", *_capability_table(BANNED),
        "", "## Configured agents", "",
    ]
    for cli in seats:
        lines += [
            f"### `{cli.name}` — {cli.cli_label} {cli.version}", "",
            f"- agent mode: `--agent-mode {cli.agent_mode}`",
            f"- image: `{cli.dockerfile}` (`{cli.image_cli_flag}`, `{cli.image_compose_env}`)",
            f"- compose: profile `{cli.compose_profile}`, service `{cli.compose_service}`",
            f"- credential: {cli.credential.kind} mounted at `{cli.credential.container_path}`",
            f"- stream normalizer: `{cli.sidecar_module}`",
            f"- tool discovery: `{cli.tool_discovery}`",
            f"- required capabilities unavailable: {list(cli.unmet) or 'none'}",
            f"- residual capabilities: {list(cli.residual) or 'none'}",
            "", *_seat_table(cli), "",
        ]
    lines += [
        "## Differences between agents", "", *_asymmetries(), "",
        "## Add a vendor CLI", "",
        "Declare the CLI in `src/codeaction/agents/vendor/clis.py`, including one disposition",
        "for each required or restricted capability. Keep the executable version and package",
        "digest fixed in its Dockerfile, and mount only the source and credentials needed by",
        "that agent. Use the same gateway, tool schemas, budgets and output contracts.", "",
        "Its stream normalizer must produce `vendor_transcript.jsonl`, `vendor_usage.json` and",
        "`vendor_runtime_attestation.json` with the existing normalizer signature. Record the",
        "effective feature state, delivered images, tool calls and terminal event. Keep",
        "unavailable measurements explicit and retain the declared limits of residual capabilities.", "",
        "Regenerate this reference after changing declarations:", "",
        "```bash",
        ".codeaction-env/bin/python tools/render_vendor_checklist.py",
        ".codeaction-env/bin/python tools/render_vendor_checklist.py --check",
        "```", "",
    ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed page is out of date")
    args = parser.parse_args(argv)
    rendered = render()
    if args.check:
        current = DOC.read_text(encoding="utf-8") if DOC.is_file() else ""
        if current != rendered:
            print(f"{DOC} is out of date; re-render it", file=sys.stderr)
            return 1
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(rendered, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
